### ISSUE TITLE
Munkitools 5.2.1

### ISSUE THREAD

**Issue by ckarabell** [jonbrown21/Munki-Theme-Maker#1]
Just want to say, love the app, or at least the concept of it, haven't had a chance to use it yet because I just found it recently and we are running the most recent official release of munki (munkitools-5.2.1.4260). The Munki Theme Maker appears to only be compatible with munkitools up to 5.1.2. I was wondering if there is a rollout plan for the newest releases from MunkiTools. Thanks.

**Comment by tbridgejc** [comment]
Bumping this for @jonbrown21. We're up to 5.4.0 at this point.

**Comment by ckarabell** [comment]
> Bumping this for @jonbrown21. We're up to 5.4.0 at this point.

same. The biggest issue appears to be the new UI for munki tools client side, the theme make distorts it pretty badly. Otherwise it's a really great app, if only we were still running the older UI.

**Comment by ckarabell** [comment]
Bump: can we assume project is dead? been aslmost 12 months and 4 releases since this has received an update.

**Comment by ckarabell** [comment]
Closing issue. Not because it has been resolved, but because this is obviously a dead project now. Shame, it's an amazing concept, but come this November we'll be 3 years since the last update.
